### PR TITLE
fix: DeepReadonly for a union with an array of itself (#306)

### LINKED ISSUE #306: `DeepReadonly` *is excessively deep and possibly infinite* for a union with an array of itself
If there is a union includes an array of the union itself, then the union wrapped with `DeepReadonly` does not compile with the latest TypeScript.

Sample code:

```typescript
type Foo = { value: string } | Foo[];

type ReadonlyFoo = DeepReadonly<Foo>;
```

It shows the compiler error:

```
Type instantiation is excessively deep and possibly infinite. ts(2589)
```

Suggested fix is simple: add an explicit branch for arrays to [DeepReadonly](https://github.com/ts-essentials/ts-essentials/blob/6b27ee4b7849d2a2670d80000a928cd20e3981b7/lib/types.ts#L154) before `T extends {}` put: `T extends AnyArray<infer U> ? readonly DeepReadonly<U>[] : ...`

### PR DESCRIPTION
**Pull request by psmolinsky**
**Changes:**

- fix DeepReadonly for a union with an array of itself

Resolves #306

### CODE REVIEW

**Comment by Beraliv** [comment]
I will probably come back to it next weekend and merge it, sorry for the inconvenience 🙏

**Review by Beraliv — CHANGES_REQUESTED** [review]
So I've just checked tests and they failed

TS 4.2 – https://github.com/ts-essentials/ts-essentials/runs/6526631721?check_suite_focus=true
TS 4.3 – https://github.com/ts-essentials/ts-essentials/runs/6526631899?check_suite_focus=true
TS 4.4 – https://github.com/ts-essentials/ts-essentials/runs/6526632092?check_suite_focus=true
TS 4.5 – https://github.com/ts-essentials/ts-essentials/runs/6526632299?check_suite_focus=true

Let me check it in the weekend and come back to you

**Comment by psmolinsky** [comment]
Ah, it is pretty complicated with tuples. Please check my fix. I struggled to add a test using `IsExact<>` as far as TS was complaining about infinite instantiation...

**Comment by Beraliv** [comment]
Now it looks good 👍

The only thing you need to do is to run Prettier against `test/index.ts`? I found it in logs – https://github.com/ts-essentials/ts-essentials/runs/6572104837?check_suite_focus=true (maybe it's not visible here)

```bash
Run yarn test
yarn run v1.22.18
$ prettier -c **/*.ts && tsc --noEmit
Checking formatting...
[warn] test/index.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by Beraliv** [comment]
@psmolinsky hey!

Please let me know if I can help you!

**Comment by psmolinsky** [comment]
Hi @Beraliv, sry for the delay - I was off because my main work project was suspended.

Now the code style should be fine. Please check.

**Comment by Beraliv** [comment]
I forgot to mention the last thing which is the changelog 😅

Every PR is created with `.changeset/*.md`, e.g. in #308

To be able to do it, you just need to run `yarn changeset` and follow the steps

As it's the fix, I would treat it as a `patch`

The output example file can be found here – https://github.com/ts-essentials/ts-essentials/pull/308/files#diff-7e794faf521096afef791d5b8a3485e83a8af59c3f668bfc1b5c4c19bbf6c4ecR5

To be transparent what needs to be done, I will create a template so it will be easier for next contributors

Sorry for the inconvenience

**Comment by psmolinsky** [comment]
Ok, please check the commit.

**Comment by Beraliv** [comment]
@psmolinsky perfect! thank you for the contribution!

**Review by Beraliv — APPROVED** [review]
✅ great job!

**Comment by psmolinsky** [comment]
Hi @Beraliv, how do I merge it? The PR shows me "Only those with write access to this repository can merge pull requests.". So I guess you need to merge it, don't you?

**Pull request merged**
